<template>
  <div class="final-prompt">
    <div v-if="autoGeneratedPrompt || editedPrompt" class="prompt-editor">
      <n-input
        v-model:value="editedPrompt"
        type="textarea"
        placeholder="选择提示词和参数后将自动生成，也可以在此直接编辑..."
        :autosize="{ minRows: 5, maxRows: 8 }"
        @update:value="handleEdit"
      />
      <div v-if="isManuallyEdited" class="edit-hint">
        <span class="hint-icon">✏️</span>
        <span class="hint-text">已手动编辑</span>
        <n-button text @click="handleReset" class="reset-link">
          重置为自动生成
        </n-button>
      </div>
    </div>

    <div v-else class="empty-state">
      <span class="empty-icon">✨</span>
      <span class="empty-text">选择提示词和参数后将在这里显示</span>
    </div>

    <div class="actions">
      <n-button
        type="primary"
        :disabled="!currentPrompt"
        @click="handleCopy"
        class="copy-btn"
      >
        <template #icon>
          <span>📋</span>
        </template>
        {{ copied ? '已复制!' : '复制提示词' }}
      </n-button>

      <n-button
        :disabled="!hasContent"
        @click="handleClear"
        secondary
      >
        <template #icon>
          <span>🗑️</span>
        </template>
        清空所有
      </n-button>
    </div>

    <div v-if="currentPrompt" class="prompt-info">
      <span class="info-item">
        <span class="info-label">提示词数量:</span>
        <span class="info-value">{{ selectedCount }}</span>
      </span>
      <span class="info-item">
        <span class="info-label">字符数:</span>
        <span class="info-value">{{ currentPrompt.length }}</span>
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { NButton, NInput } from 'naive-ui'
import { storeToRefs } from 'pinia'
import { usePromptStore } from '@/stores/promptStore'
import { useParameterStore } from '@/stores/parameterStore'
import { PromptBuilder } from '@/utils/promptBuilder'

const promptStore = usePromptStore()
const parameterStore = useParameterStore()

const { selectedPrompts } = storeToRefs(promptStore)
const { values } = storeToRefs(parameterStore)

const copied = ref(false)
const editedPrompt = ref('')
const isManuallyEdited = ref(false)

// 计算属性：自动生成的提示词
const autoGeneratedPrompt = computed(() => {
  if (selectedPrompts.value.length === 0) {
    return ''
  }

  // 获取提示词文本列表（按时间顺序）
  const promptTexts = selectedPrompts.value
    .sort((a, b) => a.timestamp - b.timestamp)
    .map(p => p.text)

  // 组合提示词和参数
  return PromptBuilder.build(promptTexts, values.value)
})

// 当前使用的提示词（手动编辑优先）
const currentPrompt = computed(() => {
  return editedPrompt.value || autoGeneratedPrompt.value
})

// 监听自动生成的提示词变化
watch(autoGeneratedPrompt, (newVal) => {
  // 只有在未手动编辑时才自动同步
  if (!isManuallyEdited.value) {
    editedPrompt.value = newVal
  }
}, { immediate: true })

// 计算属性：选中的提示词数量
const selectedCount = computed(() => {
  return selectedPrompts.value.length
})

// 计算属性：是否有内容
const hasContent = computed(() => {
  return selectedPrompts.value.length > 0 || Object.keys(values.value).length > 0
})

// 处理手动编辑
const handleEdit = () => {
  isManuallyEdited.value = true
}

// 重置为自动生成
const handleReset = () => {
  isManuallyEdited.value = false
  editedPrompt.value = autoGeneratedPrompt.value
}

// 复制到剪贴板
const handleCopy = async () => {
  if (!currentPrompt.value) return

  try {
    await navigator.clipboard.writeText(currentPrompt.value)
    copied.value = true

    // 2秒后重置状态
    setTimeout(() => {
      copied.value = false
    }, 2000)
  } catch (error) {
    console.error('复制失败:', error)
    // 降级方案：使用传统方法
    const textarea = document.createElement('textarea')
    textarea.value = currentPrompt.value
    textarea.style.position = 'fixed'
    textarea.style.opacity = '0'
    document.body.appendChild(textarea)
    textarea.select()
    document.execCommand('copy')
    document.body.removeChild(textarea)

    copied.value = true
    setTimeout(() => {
      copied.value = false
    }, 2000)
  }
}

// 清空所有选项
const handleClear = () => {
  promptStore.clearAll()
  parameterStore.resetToDefaults()
  editedPrompt.value = ''
  isManuallyEdited.value = false
}
</script>

<style scoped>
.final-prompt {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.prompt-editor {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.prompt-editor :deep(.n-input) {
  background: linear-gradient(135deg, var(--color-green) 0%, var(--color-blue) 100%);
  border: 1px solid var(--border-light);
  border-radius: 8px;
  overflow: hidden;
}

.prompt-editor :deep(.n-input--focus) {
  border-color: var(--text-blue);
  box-shadow: 0 0 0 2px rgba(7, 89, 133, 0.2);
}

.prompt-editor :deep(.n-input__textarea-el) {
  font-family: 'Courier New', Consolas, monospace;
  font-size: 14px;
  line-height: 1.6;
  color: var(--text-primary);
  background: transparent !important;
  border: none;
  padding: 12px;
}

.prompt-editor :deep(.n-input__textarea-el):focus {
  background: transparent !important;
}

.edit-hint {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  background: var(--color-yellow);
  border: 1px solid var(--text-yellow);
  border-radius: 6px;
  font-size: 12px;
  color: var(--text-yellow);
}

.hint-icon {
  font-size: 14px;
}

.hint-text {
  font-weight: 600;
}

.reset-link {
  margin-left: auto;
  font-size: 12px;
  color: var(--text-yellow);
  text-decoration: underline;
  font-weight: 600;
}

.reset-link:hover {
  opacity: 0.8;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 40px 16px;
  background: var(--bg-tertiary);
  border: 1px dashed var(--border-color);
  border-radius: 8px;
  color: var(--text-tertiary);
  min-height: 120px;
}

.empty-icon {
  font-size: 32px;
  opacity: 0.5;
}

.empty-text {
  font-size: 13px;
  text-align: center;
}

.actions {
  display: flex;
  gap: 8px;
}

.copy-btn {
  flex: 1;
}

.prompt-info {
  display: flex;
  justify-content: space-around;
  padding: 12px;
  background: var(--bg-tertiary);
  border-radius: 6px;
  font-size: 12px;
}

.info-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
}

.info-label {
  color: var(--text-tertiary);
  font-size: 11px;
}

.info-value {
  color: var(--text-primary);
  font-weight: 700;
  font-size: 16px;
  font-family: monospace;
}

/* 暗色主题 */
:global(.dark) .prompt-editor :deep(.n-input) {
  background: linear-gradient(135deg, rgba(209, 250, 229, 0.15) 0%, rgba(224, 242, 254, 0.15) 100%);
}

:global(.dark) .prompt-editor :deep(.n-input--focus) {
  background: linear-gradient(135deg, rgba(209, 250, 229, 0.2) 0%, rgba(224, 242, 254, 0.2) 100%);
  border-color: var(--text-blue);
}
</style>
